# -------------------------
#
# iizna.
#
# iizna/rustfmt.toml
# (C) 2023 IIZNA COMMUNITY.
#
# iizna for Rustのフォーマットです。
# =========================

array_width = 60 # 配列は60文字で垂直に配置します。
attr_fn_like_width = 70 # 属性引数70文字で垂直に配置します。
binop_separator = "Front" # 二項演算子が複数行にまたがった際は前に配置します。
blank_lines_upper_bound = 1 # 行間は最大1行です。
brace_style = "SameLineWhere" # ブロックの始まりは基本構文と同じ行で、whereが入る場合のみ改行します。
chain_width = 60 # メソッドチェインは60文字で垂直に配置します。
combine_control_expr = true # 関数の引数に制御構文がある場合、始まりを1行にまとめます。
control_brace_style = "AlwaysSameLine" # 制御構文ブロックの始まりは同じ行にまとめます。
edition = "2021" # 2021エディションです。
empty_item_single_line = true # 空のブロックは構文と同じ行にまとめます。
enum_discrim_aline_threshold = 20 # 20文字以内の列挙値の宣言を揃えます。
fn_args_layout = "Tall" # 関数の引数はできるだけ平行に配置します。
fn_call_width = 60 # 関数呼び出し時の引数は60文字で垂直に配置されます。
fn_single_line = true # 処理が1行の関数は宣言と同じ行にまとめます。
force_multiline_blocks = false # クロージャの処理の改行は強制しません。
format_code_in_doc_comments = false # ドキュメントコメントに含まれるコードはフォーマットしません。
format_macro_matchars = true # マクロの引数をフォーマットします。
format_macro_bodies = true # マクロの本体をフォーマットします。
format_strings = false # 文字列リテラルはフォーマットしません。
group_imports = "StdExternalCrate" # インポートを標準、外部クレート、内部クレートの順にグループ化します。
hard_tabs = false # インデントにタブは使用しません。
hex_literal_case = "Lower" # 16進数の英字は小文字にフォーマットされます。
imports_granularity = "Crate" # インポートのブロックは、同クレートにまとめます。
imports_indent = "Block" # インポートのブロックの始まりの後に改行します。
imports_layout = "Vertical" # インポートのブロック内は垂直に配置します。
indent_style = "Block" # インデントはブロックを意識して行います。
match_arm_blocks = true # matchの=>の後が改行された場合、ブロックでラップします。
match_block_trailing_comma = true # matchの要素がブロックの場合、ブロックの終端にコンマをつけます。
max_width = 100 # 100行で改行します。
marge_derives = true # #[derive(...)]が同じものに複数定義されていた場合、1つにまとめます。
newline_style = "Unix" # 改行は'\n'です。
normalize_comments = true # 可能ならば/**/を//に変更します。
normalize_doc_attributes = true # #[doc]、#![doc]を///、//!に変換します。
overflow_delimited_expr = true # 最後の引数にブロックが来た場合、はじめを前の引数と同じ行にまとめます。
remove_nested_parents = true # 不必要にネストされた括弧を削除します。
reorder_impl_items = true # 実装の配置を型エイリアス、定数、マクロ、関数に並べ替えます。
reorder_imports = true # インポートのブロック内でアルファベット順に並べ替えます。
reorder_modules = true # モジュール宣言をアルファベット順に並べ替えます。
short_array_element_width_threshold = 10 # 配列の要素は10文字まで短いと判定されます。
single_line_if_else_max_width = 50 # else-ifは50文字で改行します。
space_after_colon = true # コロンの後に空白を加えます。
space_before_colon = false # コロンの前に空白を加えません。
space_around_range = false # ..、..=、...の前後に空白を加えません。
struct_field_aline_threshold = 20 # 構造体は差が20文字までならば揃えます。
struct_lit_single_line = true # 短い構造体の初期化は1行にまとめます。
struct_lit_width = 18 # 構造体の初期化は18文字で改行します。
struct_variant_width = 35 # 構造体のバリアントは35文字で改行します。
tab_spaces = 4 # 1タブ4空白です。
trailing_comma = "Vertical" # 垂直に配置された場合、末尾の要素にもカンマをつけます。
trailing_semicolon = true # break、continue、returnにセミコロンを追加します。
type_punctuation_density = "Wide" # 二項演算子の前後に空白を加えます。
use_field_init_shorthand = true # 可能であれば省略形の初期化をします。
use_small_heuristics = "Off" # 改行に関する設定は個別に行います。
use_try_shorthand = true # try!マクロを?演算子に変換します。
version = "One" # Rustfmtは1.0です。
where_single_line = false # where句を1行にまとめません。
wrap_comments = false # コメントは改行しません。

# Ctrl+K Ctrl+C / Ctrl+K Ctrl+U
# 以下自動生成された設定

# max_width = 100
# hard_tabs = false
# tab_spaces = 4
# newline_style = "Auto"
# indent_style = "Block"
# use_small_heuristics = "Default"
# fn_call_width = 60
# attr_fn_like_width = 70
# struct_lit_width = 18
# struct_variant_width = 35
# array_width = 60
# chain_width = 60
# single_line_if_else_max_width = 50
# wrap_comments = false
# format_code_in_doc_comments = false
# doc_comment_code_block_width = 100
# comment_width = 80
# normalize_comments = false
# normalize_doc_attributes = false
# format_strings = false
# format_macro_matchers = false
# format_macro_bodies = true
# hex_literal_case = "Preserve"
# empty_item_single_line = true
# struct_lit_single_line = true
# fn_single_line = false
# where_single_line = false
# imports_indent = "Block"
# imports_layout = "Mixed"
# imports_granularity = "Preserve"
# group_imports = "Preserve"
# reorder_imports = true
# reorder_modules = true
# reorder_impl_items = false
# type_punctuation_density = "Wide"
# space_before_colon = false
# space_after_colon = true
# spaces_around_ranges = false
# binop_separator = "Front"
# remove_nested_parens = true
# combine_control_expr = true
# short_array_element_width_threshold = 10
# overflow_delimited_expr = false
# struct_field_align_threshold = 0
# enum_discrim_align_threshold = 0
# match_arm_blocks = true
# match_arm_leading_pipes = "Never"
# force_multiline_blocks = false
# fn_args_layout = "Tall"
# brace_style = "SameLineWhere"
# control_brace_style = "AlwaysSameLine"
# trailing_semicolon = true
# trailing_comma = "Vertical"
# match_block_trailing_comma = false
# blank_lines_upper_bound = 1
# blank_lines_lower_bound = 0
# edition = "2015"
# version = "One"
# inline_attribute_width = 0
# format_generated_files = true
# merge_derives = true
# use_try_shorthand = false
# use_field_init_shorthand = false
# force_explicit_abi = true
# condense_wildcard_suffixes = false
# color = "Auto"
# required_version = "1.5.1"
# unstable_features = false
# disable_all_formatting = false
# skip_children = false
# hide_parse_errors = false
# error_on_line_overflow = false
# error_on_unformatted = false
# ignore = []
# emit_mode = "Files"
# make_backup = false