# -------------------------
#
# iizna.
#
# iizna/.rustfmt.toml
# (C) 2023 IIZNA COMMUNITY.
#
# ver 1.23.1
#
# iizna for Rustのフォーマットです。
# =========================

max_width = 100 # 100行で改行します。
hard_tabs = false # インデントにタブは使用しません。
tab_spaces = 4 # 1タブ4空白です。
newline_style = "Auto" # 改行は'/r/n'または'/n'です。
indent_style = "Block" # インデントはブロック単位で行います。
use_small_heuristics = "Off" # 改行に関する設定は個別に行います。
fn_call_width = 60 # 関数呼び出し時の引数は60文字で垂直に配置されます。
attr_fn_like_width = 70 # 属性引数70文字で垂直に配置します。
struct_lit_width = 18 # 構造体の初期化は18文字で改行します。
struct_variant_width = 35 # 構造体のバリアントは35文字で改行します。
array_width = 60 # 配列は60文字で垂直に配置します。
chain_width = 60 # メソッドチェインは60文字で垂直に配置します。
single_line_if_else_max_width = 50 # if else else-ifは50文字で改行します。
wrap_comments = false # コメントは改行しません。
format_code_in_doc_comments = false # ドキュメントコメントに含まれるコードはフォーマットしません。
# doc_comment_code_block_width = 100 # ドキュメントコメントに含まれるコードは100行で改行します。(format_code_in_doc_comments  = true)
# comment_width = 80 # コメントは80行で改行します。(format_code_in_doc_comments  = true)
normalize_comments = true # 可能ならば/**/を//に変更します。
normalize_doc_attributes = true # #[doc]、#![doc]を///、//!に変換します。
format_strings = false # 文字列リテラルはフォーマットしません。
format_macro_matchers = true # マクロの引数をフォーマットします。
format_macro_bodies = true # マクロの実装部をフォーマットします。
hex_literal_case = "Lower" # 16進数の英字は小文字にフォーマットされます。
empty_item_single_line = true # 空のブロックは構文と同じ行にまとめます。
struct_lit_single_line = true # 短い構造体の初期化は1行にまとめます。
fn_single_line = true # 処理が1行の関数は宣言と同じ行にまとめます。
where_single_line = false # where句を1行にまとめません。
imports_indent = "Block" # インポートのブロックの始まりの後に改行します。
imports_layout = "Vertical" # インポートのブロック内は垂直に配置します。
imports_granularity = "Crate" # インポートのブロックは、同クレートにまとめます。
group_imports = "StdExternalCrate" # インポートを標準、外部クレート、内部クレートの順にグループ化します。
reorder_imports = true # インポートのブロック内でアルファベット順に並べ替えます。
reorder_modules = true # モジュール宣言をアルファベット順に並べ替えます。
reorder_impl_items = true # 実装の配置を型エイリアス、定数、マクロ、関数に並べ替えます。
type_punctuation_density = "Wide" # 二項演算子の前後に空白を加えます。
space_before_colon = false # コロンの前に空白を加えません。
space_after_colon = true # コロンの後に空白を加えます。
spaces_around_ranges = false # '..'、'..='および'...'の前後に空白を加えません。
binop_separator = "Front" # 二項演算子が複数行にまたがった際は前に配置します。
remove_nested_parens = true # ネストされた括弧を削除します。
combine_control_expr = true # 関数の引数に制御構文がある場合、始まりを1行にまとめます。
short_array_element_width_threshold = 10 # 配列の要素は10文字まで短いと判定されます。
overflow_delimited_expr = true # 最後の引数にブロックが来た場合、はじめを前の引数と同じ行にまとめます。
struct_field_align_threshold = 20 # 構造体は差が20文字までならば揃えます。
enum_discrim_align_threshold = 20 # 20文字以内の列挙値の宣言を揃えます。
match_arm_blocks = true # matchの=>の後が改行された場合、ブロックでラップします。
match_arm_leading_pipes = "Never" # matchの条件の前に|を加えません。
force_multiline_blocks = false # クロージャの処理の改行は強制しません。
fn_args_layout = "Tall" # 関数の引数はできるだけ平行に配置します。
brace_style = "SameLineWhere" # ブロックの始まりは基本構文と同じ行で、whereが入る場合のみ改行します。
control_brace_style = "AlwaysSameLine" # 制御構文ブロックの始まりは同じ行にまとめます。
trailing_semicolon = true # break、continue、returnにセミコロンを追加します。
trailing_comma = "Vertical" # 垂直に配置された場合、末尾の要素にもカンマをつけます。
match_block_trailing_comma = true # matchの要素がブロックの場合、ブロックの終端にコンマをつけます。
blank_lines_upper_bound = 1 # 行間は最大1行です。
blank_lines_lower_bound = 0 # 行間は最小0行です。
edition = "2021" # Rustのエディションは2021です。
version = "One" # Rustfmtは1.0です。
inline_attribute_width = 0 # 属性はアイテムとは別行です。
format_generated_files = true # 生成されたファイルをフォーマットします。
merge_derives = true # 複数のderiveを 1 つにまとめます。
use_try_shorthand = true # try!マクロを?演算子に変換します。
use_field_init_shorthand = true # 可能であれば省略形の初期化をします。
force_explicit_abi = true # 'extern "C"'の'"C"'を省略しません。
condense_wildcard_suffixes = false # タプル上のワイルドカードを..に置き換えません。
color = "Auto" # カラー出力は任意に行われます。
# required_version = "1.5.1" # rustfmtのバージョンは指定のものを使用してください。
unstable_features = false # unstableフィーチャーは無効です。
disable_all_formatting = false # 再フォーマットされます。
skip_children = false # ライン モジュール外で再フォーマットしません。
hide_parse_errors = false # 解析に失敗した場合エラーが表示されます。
error_on_line_overflow = false # コメント以外のすべての行の取得に失敗した場合のエラーはrustfmtのバグ以外ないため発生させません。
error_on_unformatted = false # すべてのコメント行の取得に失敗した場合のエラーは発生させません。
ignore = [] # フォーマット対象外のファイルはありません。
emit_mode = "Files" # (内部オプション)
make_backup = false # (内部オプション)