# --------------------
# 
# iizna.
#
# iizna/iizna_uti/Cargo.toml
# (C) 2023 IIZNA COMMUNITY.
# 
# iizna_utiの設定です。
# ====================

[package]
name = "iizna_uti"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]